# Generated by Django 2.0.6 on 2018-06-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackpot', '0002_hexabet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jackpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(verbose_name='Date Published')),
                ('content', models.TextField(blank=True, null=True)),
                ('country', models.CharField(max_length=200)),
                ('home_team', models.CharField(max_length=200)),
                ('away_team', models.CharField(max_length=200)),
                ('home_odds', models.DecimalField(decimal_places=2, max_digits=30)),
                ('draw_odds', models.DecimalField(decimal_places=2, max_digits=30)),
                ('away_odds', models.DecimalField(decimal_places=2, max_digits=30)),
                ('prediction', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='hexabet',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
