# Generated by Django 2.0.6 on 2018-06-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackpot', '0003_auto_20180630_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='punter',
            name='safety',
            field=models.CharField(default='', max_length=200),
        ),
    ]
