# Generated by Django 2.0.6 on 2018-07-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackpot', '0004_punter_safety'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punter',
            name='safety',
        ),
        migrations.AddField(
            model_name='hexabet',
            name='safety',
            field=models.CharField(default='', max_length=200),
        ),
    ]
