# Generated by Django 2.0.6 on 2018-07-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jackpot', '0005_auto_20180701_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hexabet',
            name='content',
        ),
    ]
