# Generated by Django 2.0.6 on 2018-07-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackpot', '0007_singlebet'),
    ]

    operations = [
        migrations.AddField(
            model_name='jackpot',
            name='no',
            field=models.CharField(default='', max_length=200),
        ),
    ]
