# Generated by Django 2.0.6 on 2018-07-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jackpot', '0008_jackpot_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jackpot',
            name='away_odds',
        ),
        migrations.RemoveField(
            model_name='jackpot',
            name='draw_odds',
        ),
        migrations.RemoveField(
            model_name='jackpot',
            name='home_odds',
        ),
    ]
